//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Xrm.WebResources.SelectFetchXmlView.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class selectfetchxmlviewmessages_1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal selectfetchxmlviewmessages_1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rms.Xrm.WebResources.SelectFetchXmlView.resx.selectfetchxmlviewmessages.1033", typeof(selectfetchxmlviewmessages_1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field not found in form.
        /// </summary>
        internal static string FieldNotFoundInForm {
            get {
                return ResourceManager.GetString("FieldNotFoundInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter.
        /// </summary>
        internal static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No view selected.
        /// </summary>
        internal static string NoViewSelected {
            get {
                return ResourceManager.GetString("NoViewSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Views.
        /// </summary>
        internal static string SystemViews {
            get {
                return ResourceManager.GetString("SystemViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Views.
        /// </summary>
        internal static string UserViews {
            get {
                return ResourceManager.GetString("UserViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and query are different, to update.
        /// </summary>
        internal static string ViewAndQueryAreDifferentToUpdate {
            get {
                return ResourceManager.GetString("ViewAndQueryAreDifferentToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and query matched.
        /// </summary>
        internal static string ViewAndQueryMatched {
            get {
                return ResourceManager.GetString("ViewAndQueryMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View not found.
        /// </summary>
        internal static string ViewNotFound {
            get {
                return ResourceManager.GetString("ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View type not found.
        /// </summary>
        internal static string ViewTypeNotFound {
            get {
                return ResourceManager.GetString("ViewTypeNotFound", resourceCulture);
            }
        }
    }
}
